# Network
bind 0.0.0.0
protected-mode yes
port 6379

# Memory
maxmemory 512mb
maxmemory-policy allkeys-lru

# Persistence
save 900 1
save 300 10
save 60 10000
appendonly yes
appendfsync everysec

# Logging
loglevel notice

# Slow Log
slowlog-log-slower-than 10000
slowlog-max-len 128

# Performance
hash-max-ziplist-entries 512
activerehashing yes
