framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: onlyroll_app

        # Redis pour le cache applicatif
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'

        # Pool dédié pour la gestion de la présence
        pools:
            cache.presence:
                adapter: cache.adapter.redis
                default_lifetime: 120 # 2 minutes (plus que le timeout de présence)
