nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept']
        expose_headers: ['Link', 'X-Total-Count', 'Content-Type']
        max_age: 3600
        allow_credentials: true

    paths:
        '^/':
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept']
            expose_headers: ['Link', 'X-Total-Count', 'Content-Type']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_credentials: true