[PHP]
; Debug
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
log_errors = On

; Xdebug
xdebug.mode = develop,debug,coverage
xdebug.start_with_request = yes
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003
xdebug.idekey = PHPSTORM

; Opcache (désactivé en dev)
opcache.enable = 0
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0
